name: Build, Push and Deploy on Scaleway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.16'

      - name: Build backend
        working-directory: ./back
        run: npm install

      - name: Build frontend
        working-directory: ./front
        run: |
          npm install
          npm run build

      - name: Login to Scaleway registry
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        run: |
          echo "$SCW_SECRET_KEY" | docker login rg.fr-par.scw.cloud -u "$SCW_ACCESS_KEY" --password-stdin

      - name: Build Docker image for API
        run: docker build -t rg.fr-par.scw.cloud/namespace-laldy-adan/devops-dev-api:latest ./back

      - name: Build Docker image for Web
        run: docker build -t rg.fr-par.scw.cloud/namespace-laldy-adan/devops-dev-web:latest ./front

      - name: Push Docker images to Scaleway registry
        run: |
          docker push rg.fr-par.scw.cloud/namespace-laldy-adan/devops-dev-api:latest
          docker push rg.fr-par.scw.cloud/namespace-laldy-adan/devops-dev-web:latest

      - name: Install Scaleway CLI
        run: |
          curl -L -o scw https://github.com/scaleway/scaleway-cli/releases/download/v2.16.0/scaleway-cli_2.16.0_linux_amd64
          chmod +x scw
          sudo mv scw /usr/local/bin/scw
          scw version

      - name: Deploy backend container
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: 4f182147-90a1-46a7-b7b3-babadf6177b2
          SCW_DEFAULT_ORGANIZATION_ID: 909c2e48-12fc-47bf-b8ef-360a60b07500
          SCW_DEFAULT_REGION: fr-par
        run: |
          scw container container update devops-dev-api \
            registry-image=rg.fr-par.scw.cloud/namespace-laldy-adan/devops-dev-api:latest \
            environment-variables.DATABASE_URL="file:./dev.db" \
            environment-variables.JWT_SECRET="secret" \
            environment-variables.BCRYPT_SALT_ROUNDS="10" \
            environment-variables.DEFAULT_ADMIN_PASSWORD="changeme" \
            environment-variables.PORT="3000" \
            min-scale=0 max-scale=1 memory-limit=256 cpu-limit=100 \
            redeploy=true || \
          scw container container create \
            name=devops-dev-api \
            namespace-id=4f182147-90a1-46a7-b7b3-babadf6177b2 \
            registry-image=rg.fr-par.scw.cloud/namespace-laldy-adan/devops-dev-api:latest \
            port=3000 region=fr-par \
            environment-variables.DATABASE_URL="file:./dev.db" \
            environment-variables.JWT_SECRET="secret" \
            environment-variables.BCRYPT_SALT_ROUNDS="10" \
            environment-variables.DEFAULT_ADMIN_PASSWORD="changeme" \
            environment-variables.PORT="3000" \
            min-scale=0 max-scale=1 memory-limit=256 cpu-limit=100 \
            redeploy=true

      - name: Deploy frontend container
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: your-project-id
          SCW_DEFAULT_REGION: fr-par
        run: |
          scw container container update devops-dev-web \
            registry-image=rg.fr-par.scw.cloud/namespace-laldy-adan/devops-dev-web:latest \
            environment-variables.VITE_API_URL="https://nslaldyadanbxh6co34-devops-dev-api.functions.fnc.fr-par.scw.cloud" \
            min-scale=0 max-scale=1 memory-limit=256 cpu-limit=100 \
            redeploy=true || \
          scw container container create \
            name=devops-dev-web \
            namespace-id=4f182147-90a1-46a7-b7b3-babadf6177b2 \
            registry-image=rg.fr-par.scw.cloud/namespace-laldy-adan/devops-dev-web:latest \
            port=80 region=fr-par \
            environment-variables.VITE_API_URL="https://nslaldyadanbxh6co34-devops-dev-api.functions.fnc.fr-par.scw.cloud" \
            min-scale=0 max-scale=1 memory-limit=256 cpu-limit=100 \
            redeploy=true
      
